drop table carrier cascade;
drop table delivery_require_deal;
drop table delivery_performance;
drop table delivery_agreement cascade ;
drop table delivery_require ;
drop table factory cascade ;
drop table item cascade ;
drop table item_factory_production;
drop table planet;
drop table sector cascade ;
drop table sector_restrict_come;
drop table sector_come_price;
drop table sector_restrict_import;
drop table space_pirate;
drop table way;